import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {RadioTower,Check,X} from 'lucide-react';
export function PlaybackSourcePicker({value='auto',onChange,compact=false,deezer=false}:{value?:string;onChange:(v:string)=>void;compact?:boolean;deezer?:boolean}){
  const [position,setPosition]=useState<{top:number;left:number}>(),button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!position)return;const close=(e:Event)=>{if(!menu.current?.contains(e.target as Node)&&!button.current?.contains(e.target as Node))setPosition(undefined);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPosition(undefined);button.current?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[position]);
  const options=[['auto','Автовыбор','Spotify при подключённом Premium, затем доступный источник'],['soundcloud','SoundCloud','Полная запись, если доступна'],['youtube','YouTube','Запись артиста'],['deezer','Deezer','Предпрослушивание · до 30 с'],['spotify','Spotify','В браузере или на выбранном устройстве Connect']];
  return <><button ref={button} className={compact?'source-icon':'secondary-button'} aria-label="Источник воспроизведения" aria-expanded={!!position} onClick={()=>{if(position){setPosition(undefined);return;}const r=button.current!.getBoundingClientRect();setPosition({left:Math.max(8,Math.min(r.left,innerWidth-288)),top:Math.max(8,Math.min(r.bottom+8,innerHeight-350))});}}><RadioTower size={16}/>{!compact&&(options.find(o=>o[0]===value)?.[1]||'Источник')}</button>{position&&createPortal(<div className="source-popover" ref={menu} style={position} role="dialog" aria-label="Выбрать источник"><div className="source-popover-title">Источник<button aria-label="Закрыть" onClick={()=>setPosition(undefined)}><X size={16}/></button></div>{options.map(([id,label,hint])=><button key={id} disabled={id==='deezer'&&!deezer} onClick={()=>{onChange(id);setPosition(undefined);button.current?.focus();}} aria-pressed={value===id}><span><strong>{label}</strong><small>{hint}</small></span>{value===id&&<Check size={16}/>}</button>)}</div>,document.body)}</>;
}
