import './style.css';
import {parseLyricsFile} from './utils/lyricsParser.js';
const root=document.querySelector<HTMLDivElement>('#app')!;
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let page='pending',selected:any=null,items:any[]=[],uploadLines:any,uploadName='',busy=false;
async function api(url:string,options:RequestInit={}){
  const r=await fetch(url,{...options,headers:{'Content-Type':'application/json'}});
  const json=await r.json();if(!r.ok){if(r.status===401)login();throw new Error(json.error?.message||'Ошибка запроса');}return json.data;
}
function notice(text:string){document.querySelector('#notice')!.textContent=text;}
async function action(fn:()=>Promise<void>){if(busy)return;busy=true;root.setAttribute('aria-busy','true');try{await fn();}catch(e){notice((e as Error).message);}finally{busy=false;root.removeAttribute('aria-busy');}}
function login(){root.innerHTML=`<main class="login"><span class="eyebrow">ОСКОЛОК / STUDIO</span><h1>Студия текстов</h1><p>Проверяйте, редактируйте и публикуйте.</p><form id="login"><label>Пароль разработчика<input name="password" type="password" autocomplete="current-password" required/></label><button>Войти</button></form><p role="alert" id="notice"></p></main>`;root.querySelector('form')!.onsubmit=e=>{e.preventDefault();void action(async()=>{await api('/session',{method:'POST',body:JSON.stringify({password:new FormData(e.target as HTMLFormElement).get('password')})});await dashboard();});};}
async function dashboard(){
  items=page==='upload'?[]:await api(page==='published'?'/api/lyrics':`/api/submissions?status=${page}`);
  root.innerHTML=`<header><a href="/" class="brand">◈ осколок <span>STUDIO</span></a><button id="logout" class="quiet">Выйти</button></header><main><div class="heading"><div><span class="eyebrow">ПАНЕЛЬ РАЗРАБОТЧИКА</span><h1>Слова обретают голос.</h1><p>Заявки сообщества и опубликованные тексты.</p></div><button id="refresh" class="quiet">Обновить</button></div><nav aria-label="Разделы панели">${[['pending','На проверке'],['approved','Одобрено'],['rejected','Отклонено'],['published','Опубликовано'],['upload','Загрузить текст']].map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}">${label}</button>`).join('')}</nav><p role="status" id="notice"></p><section id="workspace"></section></main>`;
  root.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>void action(async()=>{page=b.dataset.page!;selected=null;await dashboard();}));
  root.querySelector<HTMLButtonElement>('#refresh')!.onclick=()=>void action(dashboard);
  root.querySelector<HTMLButtonElement>('#logout')!.onclick=()=>void action(async()=>{await api('/session',{method:'DELETE',body:'{}'});login();});
  if(page==='upload'){upload();return;}
  const workspace=root.querySelector('#workspace')!;
  workspace.innerHTML=`<div class="queue"><span class="eyebrow">${items.length} ТЕКСТОВ · ПОСЛЕДНИЕ 200</span>${items.map(s=>`<button class="item" data-id="${escape(s.id)}"><strong>${escape(s.trackTitle)}</strong><span>${escape(s.artistName)}</span><small>${escape(s.author?.username?'@'+s.author.username:s.credit)}</small></button>`).join('')||'<p class="empty">Здесь пока нет текстов.</p>'}</div><article id="detail" class="detail"><div class="empty">Выберите текст слева, чтобы прочитать разметку и принять решение.</div></article>`;
  workspace.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.onclick=()=>{selected=items.find(s=>s.id===b.dataset.id);detail();});
}
function download(s:any){const url=URL.createObjectURL(new Blob([JSON.stringify({trackId:s.trackId,lines:JSON.parse(s.lyricsData)},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${s.trackTitle.replace(/[^\p{L}\p{N} -]/gu,'')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function detail(){const s=selected;if(!s)return;
  root.querySelectorAll('[data-id]').forEach(b=>b.classList.toggle('selected',(b as HTMLElement).dataset.id===s.id));
  const lines=JSON.parse(s.lyricsData);
  root.querySelector('#detail')!.innerHTML=`<span class="eyebrow">${escape(s.status||'Опубликовано')}</span><h2>${escape(s.trackTitle)}</h2><p>${escape(s.artistName)} · ${escape(s.credit)}</p><p class="meta">${escape(s.trackId)}${s.fileName?' · '+escape(s.fileName):''}</p><button id="download" class="quiet">Скачать разметку JSON</button><div class="preview">${lines.map((l:any)=>`<div><time>${Number(l.time).toFixed(2)} с</time><p>${escape(l.text)}${l.background?.map((b:any)=>`<small>Бэк-вокал: ${escape(b.text)}</small>`).join('')||''}</p></div>`).join('')}</div>${s.status==='pending'?'<label>Комментарий автору<textarea id="note" maxlength="1000" placeholder="Что нужно поправить или уточнить"></textarea></label><div class="actions"><button id="approve">Одобрить и опубликовать</button><button id="reject" class="quiet">Отклонить</button></div>':s.reviewNote?`<p>Комментарий: ${escape(s.reviewNote)}</p>`:''}${page==='published'?'<button id="remove" class="quiet danger">Снять с публикации</button>':''}`;
  root.querySelector<HTMLButtonElement>('#download')!.onclick=()=>download(s);
  for(const [id,decision]of [['approve','approved'],['reject','rejected']]){const b=root.querySelector<HTMLButtonElement>('#'+id);if(b)b.onclick=()=>void action(async()=>{await api(`/api/submissions/${encodeURIComponent(s.id)}/review`,{method:'POST',body:JSON.stringify({decision,reviewNote:root.querySelector<HTMLTextAreaElement>('#note')!.value})});await dashboard();notice(decision==='approved'?'Текст опубликован.':'Заявка отклонена. Комментарий доступен автору.');});}
  const remove=root.querySelector<HTMLButtonElement>('#remove');if(remove)remove.onclick=()=>void action(async()=>{await api(`/api/lyrics/${encodeURIComponent(s.id)}`,{method:'DELETE',body:'{}'});await dashboard();notice('Текст снят с публикации.');});
}
function upload(){uploadLines=undefined;uploadName='';root.querySelector('#workspace')!.innerHTML=`<form id="upload" class="upload"><h2>Опубликовать свой текст</h2><p>Только разработчик может публиковать без очереди проверки.</p><label>ID трека<input name="trackId" required placeholder="soundcloud:123456" maxlength="200"/></label><label>Название<input name="trackTitle" required maxlength="300"/></label><label>Исполнитель<input name="artistName" required maxlength="200"/></label><label>Авторство разметки<input name="credit" required maxlength="160"/></label><label>Файл TTML, LRC или JSON<input id="file" type="file" accept=".ttml,.xml,.lrc,.json" required/></label><p id="file-info"></p><button>Опубликовать</button><a href="https://guides.spicylyrics.org/s/ttml" target="_blank" rel="noopener noreferrer">Гайд по TTML — предоставлен Spicy Lyrics ↗</a></form>`;
  root.querySelector<HTMLInputElement>('#file')!.onchange=e=>void action(async()=>{uploadLines=undefined;uploadName='';const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>1000000)throw new Error('Максимальный размер — 1 МБ.');uploadLines=parseLyricsFile(await file.text(),file.name);uploadName=file.name;root.querySelector('#file-info')!.textContent=`${uploadLines.length} строк, разметка готова.`;});
  root.querySelector<HTMLFormElement>('#upload')!.onsubmit=e=>{e.preventDefault();void action(async()=>{if(!uploadLines)throw new Error('Сначала выберите корректный файл.');const form=Object.fromEntries(new FormData(e.target as HTMLFormElement));await api('/api/lyrics',{method:'POST',body:JSON.stringify({...form,lines:uploadLines,fileName:uploadName})});page='published';await dashboard();notice('Текст опубликован.');});};
}
api('/session').then(s=>s.authenticated?dashboard():login()).catch(e=>{login();notice(e.message);});
